language: cpp

compiler:
  - clang
  - gcc
cache:
  - apt
os:
  - osx
  - linux

before_install:
  # update packages
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y build-essential cmake libev4 libev-dev libtool libpcap0.8 libpcap-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf cmake-3.3.2.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd cmake-3.3.2 && ./configure && make && sudo make install && cd .. ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://github.com/msgpack/msgpack-c/releases/download/cpp-1.2.0/msgpack-1.2.0.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf msgpack-1.2.0.tar.gz ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd msgpack-1.2.0 && ./configure --prefix=/usr && make && sudo make install && cd .. ; fi  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install msgpack libev ; fi
  - git clone https://github.com/m-mizutani/libfluent.git
  - cd libfluent && cmake . && make && sudo make install && cd ..
       
before_script:  
  - cmake .

script:
  - make
  - sudo ./bin/devourer-test
